### ISSUE TITLE
The rightshift in place operator in python (>>=) is rendered wrong in atom

### ISSUE THREAD

**Issue by roSievers** [larsenwork/monoid#149] opened 2015-12-25 22:01 UTC
The right shift in place operator (>>=) available in python is rendered as >≥ in atom with monoid. I would expect it to render as >>=, maybe with a ligature for the >> part, but I can cope without.

I'm not sure if this is monoid's fault, as >>= is rendered differently in Haskell documents, so apparently there is some language differentiation going on somewhere.

**Comment by larsenwork** [comment] 2016-06-18 07:51
@roSievers I can't see this in the font editor or in Atom, could you provide more details on how to reproduce?
![screen shot 2](https://cloud.githubusercontent.com/assets/3859425/16169763/12d042c4-353a-11e6-8825-ac22ade5d7da.png)

**Comment by larsenwork** [comment] 2016-06-18 10:06
closing this as I can't reproduce but please reopen is issue persists

**Closed by larsenwork** 2016-06-18 10:06 UTC

**Comment by roSievers** [comment] 2016-06-18 13:35
Python code:
![collapseindex](https://cloud.githubusercontent.com/assets/757602/16171155/8c0fff5c-3568-11e6-8c95-f27d567f5b26.png)

Haskell code:
![works-in-haskell](https://cloud.githubusercontent.com/assets/757602/16171198/2eae61e0-3569-11e6-9923-3598d93f1da4.png)

Is the font expected to look different depending on the context?

I'm (now) running Atom 1.8 on an Ubuntu 14.04 LTS. I'm not sure how to find out which version of monoid is used. I guess it was up do date on 25 Dec 2015. (When I posted this issue.)

Is there information I could give you to narrow the issue down?

**Comment by roSievers** [comment] 2016-06-18 13:57
I just installed Atom+monoid on my 2nd laptop which runs a (almost) fresh install of Ubuntu 14.04 (I keep it around for guests). I have the same issue there.
