### ISSUE TITLE
Corruption on Archlinux

### ISSUE THREAD

**Issue by vodik** [larsenwork/monoid#31] opened 2015-06-16 02:50 UTC
Hey, so I saw your article today and thought I'd give this font a shot. However, trying it on Archlinux I see glyphs getting mixed up. Here's a code snippet with Envy Code R:
![Envy Code R][1]
vs Monoid
![Monoid][2]. I see `*` and `x` and `=` and `≤` getting mixed up. Additionally (not visible in the screenshot), '<' displays as a space.

Another guy on the #archlinux IRC channel also gave it a shot and he sees similar problems. https://i.imgur.com/Mvjsf0W.png

This is the [PKGBUILD I used](https://aur.archlinux.org/packages/tt/ttf-monoid-git/PKGBUILD) (from AUR). Not sure if this is a correct way to build the font, but even if I replace the build line to `python3 ./build.py` and package all the resulting ttf files, I see the same problems. The patch just replaces a few instances of `xrange` with `range` to get the thing to run.

  [1]: https://cloud.githubusercontent.com/assets/216803/8174927/e0fc1102-13b0-11e5-9f5e-dec31048a174.png
  [2]: https://cloud.githubusercontent.com/assets/216803/8174928/e316303a-13b0-11e5-947e-7cf909b38d10.png

**Comment by chase** [comment] 2015-06-16 03:03
I have no idea why that PKGBUILD is trying to build the font when the latest version is always available from https://cdn.rawgit.com/larsenwork/monoid/release/Monoid.ttf.zip

That's a lot of useless work to achieve something our build script does automatically.

Could you try using the TTF from that zip file?

**Comment by vodik** [comment] 2015-06-16 03:03
Okay, looking at a few more applications, maybe I shouldn't be surprised gvim can't handle it correctly. So some additional observations:

- emacs works perfectly but doesn't attempt ligatures
- libreoffice and gedit both get the ligatures but screw up spacing and also get the `*` -> `x` wrong: 
![1434423859](https://cloud.githubusercontent.com/assets/216803/8175052/9d60560e-13b2-11e5-9783-bdd2655e5beb.png)

**Comment by vodik** [comment] 2015-06-16 03:03
Sure, on it

**Comment by vodik** [comment] 2015-06-16 03:06
Only difference I see with the font in the zip file is that `*` now shows up correctly.

**Comment by chase** [comment] 2015-06-16 03:11
@larsenwork This definitely seems to be a regression caused by ligatures.

**Comment by larsenwork** [comment] 2015-06-16 06:06
hmm...it's technically not the ligatures but the contextual alternates that seem to cause on archlinux. I'll fire up my linux vm later today and try a couple of things.
@chase do you think it could be possible to add a disable liga+calt option to the script?

**Comment by chase** [comment] 2015-06-16 07:04
The thing is, the contextual alternates were not an issue before ligatures were added.
I could certainly try, but again, it'll have to wait until the weekend.

**Comment by larsenwork** [comment] 2015-06-16 07:13
@chase the contextual alternates are used together with ligatures and were added at the same time.
https://medium.com/@larsenwork/ligatures-coding-fonts-5375ab47ef8e#ca6e

**Comment by chase** [comment] 2015-06-16 10:27
Ah, shows how much I know about fonts and typography, hahaha. I thought contextual alternates were just the `glyph.alt` in the font, didn't realize there was such a feature.

**Comment by larsenwork** [comment] 2015-06-16 10:39
That's stylistic alternates - whole different thing (although we're using those too) :wink:

**Comment by chase** [comment] 2015-06-16 15:49
For what it is worth, XFT and font rendering in general is pretty behind the times in Linux land.

**Comment by larsenwork** [comment] 2015-07-14 06:49
@vodik could you try one of the "nocalt" zips here: https://github.com/larsenwork/monoid/tree/release 

If that one works (it should be without the ligatures) the try whatever version you prefer from here: http://larsenwork.com/monoid/ (they all have ligatures+calt enabled).

**Comment by vodik** [comment] 2015-07-15 01:35
My findings:

- nocalt font worked perfectly but I saw no ligatures
- Installing the font from your website looked a lot better in general

However:

I picked to have the 'l', seems like it doesn't work with the bold font (and noticeable in the other screenshots where it arises (see `while` in gedit). ![gnomefonts]

Worked perfectly in gedit but spacing is a bit weird ![gedit]
(Not a big deal, imho the space around <= is too much)

Ligatures still screwed up in gvim: ![gvim1] ![gvim2]

For context:

~~~c
    size_t sep = strcspn(val, "=");
    if (val[sep] == '\0')
        return;
~~~

and

~~~c
    while (l < &b[bytes_r]) {
        size_t nl = strcspn(l, "\n");

        l[nl] = 0;
        parse_agentdata_line(l, data);
        l += nl + 1;
    }
~~~

to help understand the more problematic rendering, but in general the rendering is vastly improved. Looks like its only `<` and `=` that are incorrectly rendered now!

I see the same problems directly in gnome terminal ![gnometerminal]

  [gnomefonts]: https://cloud.githubusercontent.com/assets/216803/8688850/ff57dea4-2a6e-11e5-8cb2-faf67805b4a8.png
  [gedit]: https://cloud.githubusercontent.com/assets/216803/8688855/02e5d986-2a6f-11e5-9162-b7646fbdcde1.png
  [gvim1]: https://cloud.githubusercontent.com/assets/216803/8688856/041d2070-2a6f-11e5-9985-2968953a0471.png
  [gvim2]: https://cloud.githubusercontent.com/assets/216803/8688857/051c90a0-2a6f-11e5-9ae8-00de2f4febf5.png
  [gnometerminal]: https://cloud.githubusercontent.com/assets/216803/8688862/08c19b88-2a6f-11e5-9cc6-5c3b17bd4734.png

**Comment by larsenwork** [comment] 2015-07-15 09:03
The "l" is simply because bold is only 90% finished. 
The <= is that still the nocalt version? 
"Liga" ligatures are only used for the social icons - the rest is created using calt.
https://medium.com/@larsenwork/ligatures-coding-fonts-5375ab47ef8e#4be8

**Comment by larsenwork** [comment] 2015-07-15 12:19
@vodik I agree about ≤≥≠ - they'll be wider in next update
![screen shot 2015-07-15 at 14 16 30](https://cloud.githubusercontent.com/assets/3859425/8698242/87593bbc-2afc-11e5-9693-dcc2153a13af.png)

**Comment by larsenwork** [comment] 2015-07-17 10:04
@vodik ping :smile:

**Comment by vodik** [comment] 2015-07-24 04:20
@larsenwork haven't forgotten, just been kept busy. I'll have something for you Sunday.

**Comment by bitwave** [comment] 2015-07-25 17:34
maybe this helps :)

https://aur.archlinux.org/packages/ttf-monoid/

**Comment by plgruener** [comment] 2015-07-27 09:27
I can confirm, there's a Problem with gVim/Vim (Terminal) (tested under Ubuntu/Linux).
[Hasklig] (https://github.com/i-tu/Hasklig#editor-support) and [FiraCode](https://github.com/tonsky/FiraCode#editor-support) do also state that.
(Maybe adjust the issue-title ?)

**Comment by larsenwork** [comment] 2015-07-27 10:16
@plgruener What's the problem you're experiencing in Linux terminals? Screenshots/description...

**Comment by plgruener** [comment] 2015-07-27 10:25
I've updated the previous comment.

**Comment by larsenwork** [comment] 2015-07-27 10:34
Does this also happen in the nocalt version?

**Comment by ajpaulson** [comment] 2015-07-27 10:35
I also got this issue on Ubuntu with a US keymap - I did not test it inside an editor, I saw the issue in Sakura term and Gnome terminal.

**Comment by larsenwork** [comment] 2015-07-27 10:36
@ajpaulson also for nocalt version?

**Comment by plgruener** [comment] 2015-07-27 10:37
No, nocalt version seems to work fine.

**Comment by larsenwork** [comment] 2015-07-27 10:39
Ok, for this issue to be fixed I'm afraid you have to raise with whoever's behind the linux terminals to add proper opentype support - the features I'm using are called "liga" and "calt"

**Comment by ajpaulson** [comment] 2015-07-27 10:41
Can confirm that NoCalt works correctly - I haven't seen this happen with any other font. Are you the only font creator making use of 'liga' and 'calt'?

**Comment by larsenwork** [comment] 2015-07-27 10:43
For monospaced fonts I'm pretty sure no one else uses "calt"
"liga" is used by other fonts with ligatures.
The problems reported are all related to calt.

**Comment by larsenwork** [comment] 2015-07-27 10:44
And I can't do what I do using only liga :smile:

**Comment by ajpaulson** [comment] 2015-07-27 10:52
I think it may be a libvte issue actually - Gnome terminal and Sakura both use libvte.

I tested on Xterm and URXVT (neither of which use libvte) both of these worked ok.

**Comment by larsenwork** [comment] 2015-07-27 10:54
Great: https://github.com/GNOME/vte

If you have the time then please add your findings to the readme editor support section :smile:

**Comment by larsenwork** [comment] 2015-07-28 11:24
@ajpaulson please make new comments instead of edits (they don't pop up in my feed :wink:)

When you say <= doesn't work - is that in Xterm or Sakura?

**Comment by ajpaulson** [comment] 2015-07-28 11:28
Apologies - I didn't know edits didn't notify.

When I tried in Xterm and URxvt (where the standard Calt version of the font showed correctly), entering `<=` just remained as it was - I'm beginning to suspect that full support for Calt and Liga in opentype fonts is a little lacking in general.

**Comment by larsenwork** [comment] 2015-07-28 11:30
Cheers

So some (most) ligatures work but not all? Or none at all?

**Comment by ajpaulson** [comment] 2015-07-28 11:37
I think I totally misunderstood - I though you were using calt as a way to replace `<=` with `≤` 

Inputting `≤` via an alt code shows the correct ligature.

**Comment by larsenwork** [comment] 2015-07-28 11:41
No, that is exactly what I'm doing. <= should look like a wider ≤
![screen shot 2015-07-28 at 13 41 07](https://cloud.githubusercontent.com/assets/3859425/8930442/53a9dd8a-352e-11e5-906e-083e8a490c59.png)

**Comment by ajpaulson** [comment] 2015-07-29 08:57
Then this is not working in Xterm or URxvt - it seems that Calt is not fully supported in most terminal emulators on Linux (libvte based ones being the majority and not supporting at all).

some insight into the state of OpenType GSUB feature support is hinted at in this SO post from last august: http://stackoverflow.com/questions/24673444/which-opentype-gsub-features-does-qt-4-8-support

**Comment by larsenwork** [comment] 2015-07-29 09:05
@ajpaulson cheers, It'd be :bowtie: if you update the [readme](https://github.com/larsenwork/monoid/blob/master/Readme.md) with your findings.

Closing this as the corruption seems gone (at least when using nocalt version)

**Closed** 2015-07-29 09:25 UTC
Labels: help wanted

**Comment by vodik** [comment] 2015-07-30 04:57
Well looks like someone beat me to this (sorry for the delay), but yeah, downloading the latest version of this font from your site indeed works 100% as intended. Can't see anything misrendering between gvim, gnome-terminal or gedit.

Thanks for the work!

**Comment by plgruener** [comment] 2015-07-30 12:20
@larsenwork whatever you changed in v.56, the "wrong" ligatures in gvim are gone now, so it looks like the nocalt-version – except for the = which are longer now (same length as + and -).
But that's not really an issue.

**Comment by larsenwork** [comment] 2015-07-30 12:52
Cheers. The narrow "=" before was a bug.

**Comment by vodik** [comment] 2015-07-30 15:17
Actually, there is something, don't know if it should be a separate bug. `>=<=` renders correctly but `<=>=` doesn't.

![1438269358](https://cloud.githubusercontent.com/assets/216803/8986924/6e3365ca-36ac-11e5-841b-252e55cc5a17.png)

**Comment by larsenwork** [comment] 2015-07-30 15:27
can quickly be fixed...shouldn't they both be "un-ligaturised", or?

**Comment by vodik** [comment] 2015-07-30 15:44
The second you enter `<=>`, the `≤` reverts back. Add another `=` and the second bit becomes a 
ligature. 

Probably the best behaviour is to unligaturise since if someone writes `>==`, the probably expect to see `>==` and not `≥=`
