### ISSUE TITLE
Visual Studio 2013

### ISSUE THREAD

**Issue by tharibo** [larsenwork/monoid#87] opened 2015-07-28 07:54 UTC
Downloaded from website : 
Alternates: None
LineHeight: M 
Font: Normal 
Ligatures: On

Visual Studio 2013 update 3 on Windows 7 64bits Professional
![image](https://cloud.githubusercontent.com/assets/5548348/8926188/18a12038-350e-11e5-9ffe-f808d7abe8fd.png)

The fonts seems too thin, and not really smooth.
Some ligatures don't work :  for example.

**Comment by larsenwork** [comment] 2015-07-28 10:24
Cheers. 
What font size are you using? Other windows users are having trouble figuring the font size out.

Thinness is by design (to make it look sharp on low res displays) but a slightly bolder version will happen at some point.
Smooth?

Does the <!-- ligature work elsewhere? E.g. if you create a plain.txt file so there is no code highlighting going on.

**Comment by tharibo** [comment] 2015-07-28 11:56
Hey, thanks for you quick reply!

This is with font size 11:
![image](https://cloud.githubusercontent.com/assets/5548348/8930408/f69935d2-352d-11e5-8654-fe3847b01123.png)


12:
![image](https://cloud.githubusercontent.com/assets/5548348/8930426/1ea89c16-352e-11e5-8d3c-0b3e90870d7c.png)


16:
![image](https://cloud.githubusercontent.com/assets/5548348/8930429/309b3050-352e-11e5-8d99-f75b0b39a8f0.png)


24:
![image](https://cloud.githubusercontent.com/assets/5548348/8930443/5560cfbc-352e-11e5-8827-cf15455e29bb.png)


Regarding thinness, it feels to me thinner in my screenshots than in the code example on your mainsite (rendered in Google Chrome):
![image](https://cloud.githubusercontent.com/assets/5548348/8930665/0fea2eea-3530-11e5-8aea-54d5e76cd7ff.png)



Regarding smoothness, it seems like I don't have antialiasing on some characters, lesser-or-equal-than, or & for example.
![image](https://cloud.githubusercontent.com/assets/5548348/8930714/743dac82-3530-11e5-93e4-b3f0b38d6673.png)

**Comment by larsenwork** [comment] 2015-07-28 12:04
Cheers - to me it looks like all characters in Visual Studio doesn't have antialiasing? Maybe this can help http://blogs.msdn.com/b/visualstudio/archive/2010/03/15/visual-studio-2010-text-clarity-cleartype-and-aliased-fonts.aspx

Also could you try https://dl.dropboxusercontent.com/u/3019777/Monoid-Regular.ttf at 12pt and take another screenshot?

**Comment by tharibo** [comment] 2015-07-28 14:09
After downloading and overwriting the installed font, I restarted a fresh Visual Studio. The font is set at 12pt:
![image](https://cloud.githubusercontent.com/assets/5548348/8933427/019fe2a4-3543-11e5-9524-c20253879295.png)


I'm having a look at your other link.

**Comment by tharibo** [comment] 2015-07-28 14:23
ClearType is activated on my system. Interesting link though.

**Comment by larsenwork** [comment] 2015-07-29 07:53
ok, not sure how to improve rendering in Visual Studio if it looks better in chrome. Windows is unfortunately generally know for it's bad font rendering.

**Comment by larsenwork** [comment] 2015-07-29 12:43
closing this as there isn't anything I can do to fix - it looks like an issue with visual studio doing weird stuff to some letters (all the ligatures not working has the hyphen in them) so the bug report should be moved to visual studio forums if they exist `¯\_(ツ)_/¯`

**Closed by larsenwork** 2015-07-29 12:43 UTC
