### ISSUE TITLE
Diaeresis/Trema above Capital Umlauts ÄÖÜ are too high

### ISSUE THREAD

**Issue by plgruener** [larsenwork/monoid#69] opened 2015-07-26 12:13 UTC
The Trema (two dots) above the Umlaute ÄÖÜÏËŸ (capital) are too high, so that they are towering into the previous line.
Tested with Monoid downloaded from your website yesterday (LineHeight M, Normal Font, Ligatures off) under Ubuntu/Linux in Atom and GVim (and in Konsole) with lineheight=1.

As one can clearly see in the screenshot, the dots seem to be cut off in the middle by line-highlighting, and clashing with the lower j,g,p,q etc.

Using the XL-Lineheight font seems to "fix" this issue, but then the other Characters are too far apart.

![monoid-umlaute-fail](https://cloud.githubusercontent.com/assets/5796100/8893768/09c9f902-339e-11e5-8053-3e3db7ff5db2.png)

**Comment by larsenwork** [comment] 2015-07-26 17:54
It is actually by design - I used to have capitals with diacritics squeezed vertically but looked weird - especially in all caps text. Not sure how to "solve" this. I've lowered them a bit.
![screen shot 2015-07-26 at 19 53 56](https://cloud.githubusercontent.com/assets/3859425/8895151/13711698-33d0-11e5-89fe-59729ee19677.png)

**Comment by jozsefk9** [comment] 2015-07-26 17:59
I like the extra large space between lines. Could be matter of taste.


J. K.
--
N9005

**Comment by plgruener** [comment] 2015-07-26 18:12
BTW, same issue with all other accents (eg È,É,Ŝ,Ĉ, …)
I assumed it's a design„flaw“ – you want the caps as big as possible, then there's no space above…don't know if there's an elegant solution.
Problem is, in some sizes/editors I don't see the diacritics at all, so cannot tell the difference between A and Ä.
Sure, large line spacing resolves that issue, but that's against the *compact* design principle.

**Comment by larsenwork** [comment] 2015-07-26 20:51
Not a "flaw" but by design.

Added it to this poll though: http://goo.gl/forms/TlxGLPkH2e

"Solutions"
1. You can make the diacritics smaller. Would make it impossible to tell e.g. Ȅ and Ë apart. 
1. Reduce the space between the diacritic and the base character. Would also make it harder to tell them apart + maybe look weird
1. Make the capitals with diacritics shorter - i.e. squeeze them vertically. Looks strange but works.

What I originally did was the last "solution" but it looked really odd. Option B in the poll are in between what I originally made and what monoid currently has - i.e. squeezed but not that much.

**Comment by plgruener** [comment] 2015-07-26 21:20
I agree, solution 3 sounds like the way to go. I think it's acceptable for a monospaced font to have a little odd-looking diacritics (they are only used sparingly in sourcecode, if at all). The version in the poll doesn't even look too strange to me (couldn't test it on small sizes though). Maybe you can later also offer that as an alternate version.

((Yeah, by „flaw“ (not the right word) I meant other font's do avoid that problem by not having such line-filling characters (correct me if I'm wrong, definitely not a font-expert^^), but you took an interesting design-decision. ))

Anyways, keep up the good work, Monoid looks very promising :D

**Comment by plgruener** [comment] 2015-07-26 21:26
I've played a litte with some other accents, and the Ǎ (A with caron) seems a bit off… it's a straight A (not the normal slightly curved one) and is much too wide (see screenshot). I don't think that's intended? 
![monoid-a-caron](https://cloud.githubusercontent.com/assets/5796100/8895984/a0d84192-33ed-11e5-9441-4687d6ca6b8b.png)

**Comment by larsenwork** [comment] 2015-07-26 21:42
Ǎ isn't in the font (yet) - thought it wasn't really used? Otherwise add it to #12

**Comment by plgruener** [comment] 2015-07-26 22:15
Oh, I don't know if it's used, I just hit my dead-keys and the A ;D

**Comment by larsenwork** [comment] 2015-07-26 23:29
> I agree, solution 3 sounds like the way to go. I think it's acceptable for a monospaced font to have a little odd-looking diacritics (they are only used sparingly in sourcecode, if at all). The version in the poll doesn't even look too strange to me (couldn't test it on small sizes though). Maybe you can later also offer that as an alternate version.

Diacritics are used a lot in source code though so sparingly will never be an argument but I'll add the squeezed ones as a download options to regular soon.
Try searching for a common word using diacritics here on github and you'll be surprised.

**Comment by plgruener** [comment] 2015-07-27 17:39
Similar issue: the bottom curly quotes „ ‚ are too low, their curly part is in the line beneath.
![monoid-curly-quotes-fail](https://cloud.githubusercontent.com/assets/5796100/8913045/d8f0f2e6-3496-11e5-9580-46ffaa33e312.png)
(grey part in screenshot delimits line)

The upper curly quotes seem to be fine, however.

**Comment by larsenwork** [comment] 2015-07-27 17:52
@plgruener good catch - they should have been elevated like the comma

**Comment by plgruener** [comment] 2015-07-27 17:55
Also, could you add a little dot at their „big end“ (to distinguish better from the straight quotes), or would that make them too undistinctive from the comma?

**Comment by larsenwork** [comment] 2015-07-27 18:07
I think being able to distinguish them from straight quotes is more important than distinguishing single low quote from comma so I'll go with option "big end" :wink:

**Comment by larsenwork** [comment] 2015-07-27 23:15
@plgruener try this: https://dl.dropboxusercontent.com/u/3019777/Monoid-Regular.ttf

Note that I've changed the UPM so optimum font-size it's now 16px or 12pt depending on your OS. (The actual font-size is unchanged)

**Comment by plgruener** [comment] 2015-07-28 00:24
Curly quotes look great now, good job :+1:
(Now waiting for the lowered diacritics ;)

**Comment by larsenwork** [comment] 2015-07-28 12:59
En route to 0.55 so closing this

**Closed by larsenwork** 2015-07-28 12:59 UTC
Labels: question, Request

**Comment by larsenwork** [comment] 2015-07-29 01:35
are currently available as ss14 - will be hardcoded once #94 is solved

**Comment by plgruener** [comment] 2015-07-29 14:41
Thanks. But what does ss14 mean?

**Comment by larsenwork** [comment] 2015-07-29 14:57
Stylistic set number 14 - can be used via css (so e.g. atom editor), adobe programs (photoshop etc), apple programs (text edit etc)...but not in basic code editors 


https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings
http://arstype.tumblr.com/post/24539110952/accessing-opentype-features-in-apples-own-applications
